import './Legal.css';

export default function Terms() {
  return (
    <div className="legal-page animate-fade-in-up">
      <div className="legal-hero">
        <div className="legal-badge">Legal</div>
        <h1 className="legal-title">Terms and Conditions</h1>
        <p className="legal-meta">Last updated: June 20, 2026 &nbsp;·&nbsp; Effective immediately</p>
      </div>

      <div className="legal-body">

        <section className="legal-section">
          <h2>1. Acceptance of Terms</h2>
          <p>By accessing or using CVMind AI ("the Service", "we", "us"), you agree to be bound by these Terms and Conditions. If you do not agree to these terms, please do not use our service. These terms apply to all visitors, users, and others who access or use the Service.</p>
        </section>

        <section className="legal-section">
          <h2>2. Description of Service</h2>
          <p>CVMind AI provides AI-powered resume analysis, career tools, LinkedIn optimisation, interview preparation, and related career-development features (collectively, "the Service"). The Service is provided on an "as is" basis and may be updated, modified, or discontinued at any time without notice.</p>
        </section>

        <section className="legal-section">
          <h2>3. User Accounts</h2>
          <p>To access certain features you must create an account. You are responsible for:</p>
          <ul>
            <li>Maintaining the confidentiality of your account credentials.</li>
            <li>All activity that occurs under your account.</li>
            <li>Notifying us immediately of any unauthorised use at <a href="mailto:contact@manavtiwari.in">contact@manavtiwari.in</a>.</li>
          </ul>
          <p>We reserve the right to terminate accounts that violate these Terms.</p>
        </section>

        <section className="legal-section">
          <h2>4. Subscription Plans and Payments</h2>
          <p>CVMind AI offers a Free plan and a Pro subscription plan. Pro plan billing is processed securely through our payment provider. By subscribing you authorise us to charge the applicable fees on the billing cycle you selected (monthly, quarterly, or yearly). All prices are in Indian Rupees (₹) unless stated otherwise.</p>
          <p>Subscription fees are non-refundable except as described in our <strong>Refund Policy</strong>. We may change pricing with 30 days' notice.</p>
        </section>

        <section className="legal-section">
          <h2>5. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul>
            <li>Use the Service for any unlawful purpose or in violation of any applicable law.</li>
            <li>Upload malicious content, spam, or any material that infringes third-party rights.</li>
            <li>Attempt to reverse-engineer, scrape, or exploit the Service.</li>
            <li>Share, resell, or sublicense access to your account.</li>
          </ul>
        </section>

        <section className="legal-section">
          <h2>6. Intellectual Property</h2>
          <p>All content, branding, AI models, and software comprising CVMind AI are the intellectual property of CVMind AI and its licensors. You retain ownership of any resume or document you upload. By uploading content you grant us a limited, non-exclusive licence to process that content solely to provide the Service to you.</p>
        </section>

        <section className="legal-section">
          <h2>7. AI-Generated Content</h2>
          <p>Outputs generated by our AI tools are provided for informational and career-assistance purposes only. They do not constitute professional legal, financial, or career advice. You are responsible for reviewing and verifying all AI-generated content before using it in job applications or professional contexts.</p>
        </section>

        <section className="legal-section">
          <h2>8. Privacy</h2>
          <p>Your use of the Service is also governed by our Privacy Policy, which is incorporated into these Terms by reference. We process your data only as described in that policy.</p>
        </section>

        <section className="legal-section">
          <h2>9. Limitation of Liability</h2>
          <p>To the fullest extent permitted by law, CVMind AI shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service, including but not limited to loss of employment opportunities, loss of data, or business interruption.</p>
        </section>

        <section className="legal-section">
          <h2>10. Termination</h2>
          <p>We may suspend or terminate your access to the Service at any time, with or without cause, with or without notice. Upon termination, your right to use the Service ceases immediately.</p>
        </section>

        <section className="legal-section">
          <h2>11. Governing Law</h2>
          <p>These Terms shall be governed by and construed in accordance with the laws of India. Any disputes shall be subject to the exclusive jurisdiction of the courts located in New Delhi, India.</p>
        </section>

        <section className="legal-section">
          <h2>12. Changes to Terms</h2>
          <p>We reserve the right to update these Terms at any time. Continued use of the Service after changes constitutes acceptance. We will notify registered users of material changes via email.</p>
        </section>

        <section className="legal-section">
          <h2>13. Contact Us</h2>
          <p>Questions about these Terms? Contact us at <a href="mailto:contact@manavtiwari.in">contact@manavtiwari.in</a>.</p>
        </section>

      </div>
    </div>
  );
}
